- hosts: localhost
  tasks:
          - package:
                  name: "httpd"
                  state: present
          - copy:
                  src: rh.html
                  dest: "/var/www/html/"
          - replace:
                  path: "/etc/httpd/conf/httpd.conf"
                  regexp: "AllowOverride None"
                  replace: "AllowOverride AuthConfig"
          - copy:
                  src: ".htaccess"
                  dest: "/var/www/html/.htaccess"
          - pip:
                  name: "passlib"
          - htpasswd:
                    path: /etc/www.passwd
                    name: sima
                    password: 'redhat'
                    owner: root
          - service:
                  name: "httpd"
                  state: restarted
